Track needs setuptools < 82
```
 Traceback (most recent call last):
   File "/usr/local/bin/trac-admin", line 3, in <module>
     from trac.admin.console import run
   File "/usr/local/lib/python3.14/site-packages/trac/__init__.py", line 14, in <module>
     from pkg_resources import DistributionNotFound, get_distribution
 ModuleNotFoundError: No module named 'pkg_resources'
```

```
UserWarning: pkg_resources is deprecated as an API. See
https://setuptools.pypa.io/en/latest/pkg_resources.html.

The pkg_resources package is slated for removal as early as 2025-11-30.
Refrain from using this package or pin to Setuptools<81.
```