Downgrade to Python 3.13
b/c Track isn't compatible with 3.14:

```
Traceback (most recent call last):
  File "/usr/local/bin/trac-admin", line 3, in <module>
    from trac.admin.console import run
  File "/usr/local/lib/python3.14/site-packages/trac/admin/console.py", line 34, in <module>
    from trac.env import Environment
  File "/usr/local/lib/python3.14/site-packages/trac/env.py", line 42, in <module>
    from trac.db.convert import copy_tables
  File "/usr/local/lib/python3.14/site-packages/trac/db/convert.py", line 18, in <module>
    from trac.db import sqlite_backend
  File "/usr/local/lib/python3.14/site-packages/trac/db/sqlite_backend.py", line 43, in <module>
    pysqlite_version = sqlite.version_info
                       ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sqlite3' has no attribute 'version_info'
```

From https://docs.python.org/3.14/library/sqlite3.html#module-sqlite3

```
Deprecated since version 3.12, removed in version 3.14: The version and version_info constants.
```