Pin pylint-django to v2.5.3
v2.5.5 switches to pylint 3.x which errors out with:

  File "/home/runner/work/trackers-integration/Kiwi/kiwi_lint/dunder_attributes.py", line 11, in DunderClassAttributeChecker
    __implements__ = (interfaces.IAstroidChecker,)
AttributeError: module 'pylint.interfaces' has no attribute 'IAstroidChecker'